name: FINALCISCV
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.19
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - jupyter
  - pip
  - pip:
      - kagglehub
      - ipywidgets
